version: 0.2.{build}
environment:
  TARGET: x86_64-pc-windows-msvc
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.msi"
  - start /wait msiexec /i rust-nightly-%TARGET%.msi INSTALLDIR="%CD%\rust-nightly-%TARGET%" /quiet /qn /norestart
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64
  - set PATH=%PATH%;%CD%/rust-nightly-%TARGET%/bin
  - SET PATH=%PYTHONPATH%;%PATH%
  - rustc -V
  - cargo -V
  - python --version
test_script:
  - set PATH=C:\Python27-x64;%PATH%&& cargo test --verbose --features python2
  - set PATH=C:\Python34-x64;%PATH%&& cargo test --verbose --features python3
