[package]

name = "cpython"
version = "0.0.1"
description = "Bindings to Python 2.7"
authors = ["Daniel Grunwald <daniel@danielgrunwald.de>"]
readme = "README.md"
keywords = [
    "python",
    "cpython",
    "libpython27",
]
homepage = "https://github.com/dgrunwald/rust-cpython"
repository = "https://github.com/dgrunwald/rust-cpython.git"
documentation = "http://dgrunwald.github.io/rust-cpython/doc/cpython/"
license = "MIT"
exclude = [
    ".gitignore",
    ".travis.yml",
]
build = "build.rs"

[dependencies]
libc="*"
num="*"

# TODO: crates.io version doesn't have necessary conditional cfg flags yet
[dependencies.python27-sys]
git = "https://github.com/dgrunwald/rust-cpython.git"
