[package]
authors = ["Messense Lv <messense@icloud.com>"]
name = "word-count"
version = "0.1.0"

[dependencies]
rayon = "1.0"
pyo3 = { path = "../..", features = ["extension-module"] }

[lib]
name = "word_count"
crate-type = ["cdylib"]
