[package]
name = "pyo3cls"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
quote="0.3"

[dependencies.syn]
version="0.11"
features=["full"]
#git = "https://github.com/dtolnay/syn.git"
