[package]
name = "python27-sys"
version = "0.0.6"
description = "FFI Declarations for Python 2.7"
readme = "README.md"
keywords = [
    "python",
    "cpython",
    "libpython27",
]
homepage = "https://github.com/dgrunwald/rust-python27-sys"
repository = "https://github.com/dgrunwald/rust-python27-sys.git"
license = "Python-2.0"
authors = ["Daniel Grunwald <daniel@danielgrunwald.de>"]
build = "build.rs"
exclude = [
    ".gitignore",
    ".travis.yml",
]

[dependencies]
libc = "*"

# [build-dependencies]
# pkg-config = "0.3"

# TODO: depends on trunk pkg-config for now because we 
# require 14c4b9, can revert this when alex bumps the 
# crate release 
[build-dependencies.pkg-config]
git = "https://github.com/alexcrichton/pkg-config-rs.git"
